config/routes.rb
Rails.application.routes.draw do
  
  resources :usergroups
  
  get 'comments/create'
  get 'comments/destory'
  
  resources :comments
  
  resources :posts
  resources :users do
    member do
      get :following, :followers , :posts, :usergroups
    end
  end
  resources :microposts
  resources :relationships,       only: [:create, :destroy]
  
  
 resources :users do
  collection do
    post :import   #this defines : import_users POST   /users/import(.:format)   users#import
  end
end


  resources :publications
  
  
  #static_pages_controller
  get  '/about',   to: 'static_pages#about'
  get  '/help',   to: 'static_pages#help'
  get  '/search',   to: 'static_pages#search'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #user_controller
   get  '/signup', to: 'users#new'
   post '/signup',  to: 'users#create'
   
   #session_controller
   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   delete '/logout', to: 'sessions#destroy'
   
   #micropost_controller
   post '/users', to: 'microposts#create'
  
  #root 'application#hello'
   root 'static_pages#home'
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    user_id = current_user.id
    @post = Post.find(params[:post_id])
    content = params[:comment][:content]
    @post.comments.create(user_id:user_id, content:content)
    redirect_to post_path(@post)  
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = Post.find(@comment.post_id)
    @comment.destroy
    redirect_to post_path(@post)
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
       <strong><%= comment.user.name %>:</strong>
          <%= comment.content %>
          <% if logged_in? && current_user?(@post.user) %>
           <%= link_to "Delete", comment_path(comment.id), method: :delete,
                                  data: { confirm: "You sure?" } %>
                                  
                                
          <% end %>
        </p>
      </div>
    </div>
  </article>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= render 'shared/error_messages', object:f.object %>
  <div class="comment-textarea">
  	 <div><%= hidden_field_tag :use_id, @user.id %></div>
  	  <div><%= hidden_field_tag :post_id, @post.id %></div>
    <%= f.text_area :content %>
    
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>