config/routes.rb
Rails.application.routes.draw do
  
  resources :usergroups
  
  get 'comments/create'
  get 'comments/destory'
  
  resources :comments
  
  resources :posts
  resources :users do
    member do
      get :following, :followers , :posts, :usergroups
    end
  end
  resources :microposts
  resources :relationships,       only: [:create, :destroy]
  
  
 resources :users do
  collection do
    post :import   #this defines : import_users POST   /users/import(.:format)   users#import
  end
end


  resources :publications
  
  
  #static_pages_controller
  get  '/about',   to: 'static_pages#about'
  get  '/help',   to: 'static_pages#help'
  get  '/search',   to: 'static_pages#search'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #user_controller
   get  '/signup', to: 'users#new'
   post '/signup',  to: 'users#create'
   
   #session_controller
   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   delete '/logout', to: 'sessions#destroy'
   
   #micropost_controller
   post '/users', to: 'microposts#create'
  
  #root 'application#hello'
   root 'static_pages#home'
  
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<!-- <%= @feed_items.class%> -->


<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<% if current_user?(@user) %>
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object:f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(@user, size: 60), @user %>
<h1><%= @user.name %></h1>
<span><%= link_to "view my profile", @user %></span>
<span><%= link_to pluralize(@user.posts.count, "post"), posts_user_path(@user) %></span>