config/routes.rb
Rails.application.routes.draw do
  
  resources :usergroups
  
  get 'comments/create'
  get 'comments/destory'
  
  resources :comments
  
  resources :posts
  resources :users do
    member do
      get :following, :followers , :posts, :usergroups
    end
  end
  resources :microposts
  resources :relationships,       only: [:create, :destroy]
  
  
 resources :users do
  collection do
    post :import   #this defines : import_users POST   /users/import(.:format)   users#import
  end
end


  resources :publications
  
  
  #static_pages_controller
  get  '/about',   to: 'static_pages#about'
  get  '/help',   to: 'static_pages#help'
  get  '/search',   to: 'static_pages#search'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #user_controller
   get  '/signup', to: 'users#new'
   post '/signup',  to: 'users#create'
   
   #session_controller
   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   delete '/logout', to: 'sessions#destroy'
   
   #micropost_controller
   post '/users', to: 'microposts#create'
  
  #root 'application#hello'
   root 'static_pages#home'
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :logged_in_user, only: [:new, :edit, :create, :destroy]
  before_action :correct_user,   only: :destroy
  
   def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    @comments = @post.comments
    @comment = Comment.new
  end
  
  def new
    @user=current_user
    @post=Post.new
  end
  
  def create    
     @post = current_user.posts.build(post_params)
     if @post.save
      flash[:success] = "The post is saved!" 
      redirect_to user_path(current_user)
      else
        @user=current_user
        redirect_to new_post_url
      end
  end
  
   def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "The bolg is updated!" 
      redirect_to post_url(@post) 
    else
      render 'edit'
    end
    
  end
  
   def destroy
    @post.destroy
    flash[:success] = "The post is deleted"
    redirect_to root_url
  end
  
  private
    def post_params
      params.require(:post).permit(:title,:content)
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end

  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if logged_in? %>
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object:f.object %>
  <div class="field">
  	
  	<h3><%= f.label "New Post" %></h3>
    <%= f.text_field :title, class: 'form-control',placeholder: "Title..." %>
    <%= f.text_area :content, class: "tinymce",:rows => "15" %>
  </div>
  <div><%= f.submit "Post", class: "btn btn-primary" %></div>
<% end %>
<% end %>
<script>
<%= tinymce %>
</script>

app/views/posts/_post.html.erb
<div class="blog-container-home">
  
  <div class="blog-header">
      <div class="blog-author-home">
        <h3><%= link_to gravatar_for(post.user, size: 30), post.user %><%= link_to post.user.name, post.user %></h3>

      </div>
    
  </div>

  <div class="blog-body">
    <div class="blog-title">
      <h1><%= link_to post.title, post_path(post) %></h1> 
      <div class="blog-operation">
      
     <% if logged_in? && current_user?(post.user) %>
     
     <%= link_to "Edit", edit_post_path(post) %>
    | <%= link_to "Delete", post_path(post), method: :delete,
                                  data: { confirm: "You sure?" } %>
      <% end %>

</div>
    </div>
    <div class="blog-summary">
    	   <% if post.content.length > 200 %>
      <p><%= post.content.to_s[0..200] %>....<%= link_to "Mehr", post_path(post) %></p>
      <% else %>
      <p><%= post.content %></p>
      <% end %>
    </div>
  </div>
  
  <div class="blog-footer">
    <ul>
      <li class="published-date">Posted <%= time_ago_in_words(post.created_at) %> ago.</li>
      <li class="comments"><svg class="icon-bubble"><use xlink:href="#icon-bubble"></use></svg><span class="numero"><%= pluralize(post.comments.count, "comment") %></span></li>
    </ul>
  </div>

</div>
 

app/views/posts/edit.html.erb
<% provide(:title, "Edit Blog") %>
<h1>Edit your blog</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= render 'form' %>  
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		 <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
		<section class="stats">
         <%= render 'shared/stats' %>
       </section>
	</aside>
	
	<div class="col-md-8">
		
       <%= render 'form' %>
	</div>
</div>

app/views/posts/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">

	<% if logged_in? %>
	<aside class="col-md-4">

		<section class="user_info">
			<h1> <%= gravatar_for @user, size: 60 %>
			<%= @user.name %> </h1>
			<span><%= link_to pluralize(@user.posts.count, "post"), @post.user %></span>
		</section>
		<section class="stats">
			<%= render 'shared/stats' %>
		</section>
	</aside>
	<% end %>

	<% if logged_in? %>
	<div class="col-md-8">
		<% else %>
		<div class="col-md-12">
			<% end %>

			<div class="blog-container-home">

				<div class="blog-header">
					<div class="blog-author">
						<h3><%= link_to gravatar_for(@post.user, size: 30), @post.user %><%= link_to @post.user.name, @post.user %></h3>
					</div>

				</div>

				<div class="blog-body">
					<div class="blog-title">
						<h1><a href="#"><%= link_to @post.title, post_path(@post) %></a></h1>
					</div>
					<div class="blog-operation">
						<% if logged_in? && current_user?(@post.user) %>

						<%= link_to "Edit", edit_post_path(@post) %>
						| <%= link_to "Delete", post_path(@post), method: :delete,
						data: { confirm: "You sure?" } %>
						<% end %>
					</div>
					<div class="blog-summary">
						<p>
							<%= @post.content %>
						</p>
					</div>
				</div>

				<div class="blog-footer">
					<ul>
						<li class="published-date">
							Posted <%= time_ago_in_words(@post.created_at) %> ago.
						</li>
						<li class="comments">
             <span class="numero"><%= pluralize(@comments.count, "comment") %></span>
						</li>
					</ul>
				</div>

				<div class="blog-comments">		
						 <% if @comments.count > 0 %>
						 <h3>Comment:</h3>
						 <hr />
						<%@comments.each do |comment| %>
			         <%= render comment %>
			         <% end %>
						 <% end %>
						<div class="comment-form">
							<hr />
							<% if logged_in? %>
							<h3 class="subtitle is-3">Leave a comment</h3>
							<%= render 'comments/form' %>
							<% end %>
						</div>
					</div>
			</div>
		</div>
	</div>