config/routes.rb
Rails.application.routes.draw do
  
  resources :usergroups
  
  get 'comments/create'
  get 'comments/destory'
  
  resources :comments
  
  resources :posts
  resources :users do
    member do
      get :following, :followers , :posts, :usergroups
    end
  end
  resources :microposts
  resources :relationships,       only: [:create, :destroy]
  
  
 resources :users do
  collection do
    post :import   #this defines : import_users POST   /users/import(.:format)   users#import
  end
end


  resources :publications
  
  
  #static_pages_controller
  get  '/about',   to: 'static_pages#about'
  get  '/help',   to: 'static_pages#help'
  get  '/search',   to: 'static_pages#search'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #user_controller
   get  '/signup', to: 'users#new'
   post '/signup',  to: 'users#create'
   
   #session_controller
   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   delete '/logout', to: 'sessions#destroy'
   
   #micropost_controller
   post '/users', to: 'microposts#create'
  
  #root 'application#hello'
   root 'static_pages#home'
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.h-its.org/de/">HITS</a>
    by <a href="#">Xiaoming Hu</a>
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        
    <%= link_to image_tag("hits.png", id:"logo",class:"logo_icon", alt: "HITS logo", width:'236', height:'112'),
            root_path %>   
           
        <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Publications", publications_path %></li>
        <li><%= link_to "Search", search_path %></li>
        <% if logged_in? %>
          <li><%= link_to "New Post", new_post_path %></li>
          <li><%= link_to "Users List", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             <%= current_user.name %> 
             <% if current_user.admin? %> 
              (admin)
             <% end %>
             <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider" ></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </nav>
      </div>
    </header>
    

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- external scripts -->
    <%= javascript_include_tag "https://unpkg.com/itemsjs@latest/dist/itemsjs.min.js" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/vue/latest/vue.js" %>



    <%= render 'layouts/shim' %>
  </head>
  <body>
     <%= render 'layouts/header' %>
    <div class="container container_body">
     <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
       <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>